apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
spec:
  parallelism: {{.Values.parallelism}}
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 1
  template:
    metadata:
      name: {{.Values.name}}
    spec:
      imagePullSecrets:
        - name: {{.Values.imagePullSecrets.name}}
      containers:
        - name: {{.Values.name}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          volumeMounts:
            - name: {{.Values.name}}-data
              mountPath: /var/docker/{{.Values.name}}/data
            - name: {{.Values.name}}-config
              mountPath: /var/docker/{{.Values.name}}/config
      volumes:
        - name: {{.Values.name}}-data
          persistentVolumeClaim:
            claimName: crawler-pvc
        - name: {{.Values.name}}-config
          projected:
            sources:
              - configMap:
                  name: {{.Values.name}}
                  items:
                    - key: {{.Values.name}}.json
                      path: {{.Values.name}}.json
      restartPolicy: OnFailure
