apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.pvc.name}}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{.Values.pvc.storage}}
  storageClassName: {{.Values.pvc.storageClassName}}
  selector:
