debug: ${debug}
namespace: ${Namespace}
name: ${Name}
activeDeadlineSeconds: 86400

pvc:
  name: ${PVCName}

image:
  repository: ${RegistryServer}/${ImageRepository}
  tag: ${ImageTag}
  pullPolicy: Always

imagePullSecrets:
  name: ${PullSecrets}

config: |
  {
    "producer": {
      "type": "file",
      "filename": "data/analyst/www.shicimingju.com/shici.json"
    },
    "consumer": {
      "type": "mysql",
      "mysql": {
        "username": "${MysqlUsername}",
        "password": "${MysqlPassword}",
        "database": "${MysqlDatabase}",
        "host": "${MysqlServer}",
        "port": 3306,
        "connMaxLifeTime": "60s",
        "maxIdleConns": 10,
        "maxOpenConns": 20
      },
      "table": "shici",
      "fields": ["id", "title", "author", "dynasty", "content"],
      "keyMap": {
        "id": "@lineno"
      }
    },
    "parallel": 1
  }
