#!/usr/bin/env bash

Namespace="prod"
Name="go-crawler-databus"
RegistryServer="{{.registry.server}}"
RegistryUsername="{{.registry.username}}"
RegistryPassword="{{.registry.password}}"
MysqlServer="{{.mysql.server}}"
MysqlRootPassword="{{.mysql.rootPassword}}"
MysqlUsername="{{.mysql.username}}"
MysqlPassword="{{.mysql.password}}"
MysqlDatabase="ancient"
PVCName="crawler-pvc"
PullSecrets="hatlonely-pull-secrets"
ImageRepository="hatlonely/go-crawler-databus"
ImageTag="1.0.0"
ChartTpl="chart.shici2stdout.yaml"
