debug: true
namespace: prod
name: go-crawler-analyst
activeDeadlineSeconds: 86400

pvc:
  name: crawler-pvc

image:
  repository: registry.cn-beijing.aliyuncs.com/hatlonely/go-crawler-analyst
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets:
  name: hatlonely-pull-secrets

config: |
  {
    "book": {
      "root": "/Users/hatlonely/hatlonely/github.com/hatlonely/go-crawler/data/www.shicimingju.com",
      "out": "book.json"
    },
    "shiCi": {
      "root": "/Users/hatlonely/hatlonely/github.com/hatlonely/go-crawler/data/www.shicimingju.com",
      "out": "shici.json"
    }
  }
